[package]
name = "tentacle-secio"
version = "0.1.11"
license = "MIT"
description = "Secio encryption protocol for p2p"
authors = ["piaoliu <441594700@qq.com>", "Nervos Core Dev <dev@nervos.org>"]
repository = "https://github.com/nervosnetwork/p2p"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[package.metadata.docs.rs]
features = [ "molc" ]
all-features = false
no-default-features = true

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"
log = "0.4.1"

flatbuffers = { version = "0.6.0", optional = true }
flatbuffers-verifier = { version = "0.2.0", optional = true }
molecule = { version = "0.3.1", optional = true }

secp256k1 = "0.15"
hmac = "0.7.0"
sha2 = "0.8.0"
rand = "0.6"
ring = "0.16.5"
twofish = "0.2.0"
aes-ctr = "0.3.0"
aesni = { version = "0.6", default-features = false, features = ["nocheck"] }
ctr = "0.3.0"
unsigned-varint = "0.2.2"
bs58 = "0.2.0"

[dev-dependencies]
env_logger = "0.6"
criterion = "0.3"

[features]
default = []
# use flatbuffer to handshake
flatc = [ "flatbuffers", "flatbuffers-verifier" ]
# use molecule to handshake
molc = [ "molecule" ]

[[bench]]
name = "bench"
harness = false
